# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AR Location Based' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AR Location Based
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  target 'AR Location BasedTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
